export const RISK_RULES: Record<string, number> = {
  LOGIN_FAILED: 10,
  NEW_DEVICE: 30,
  IP_CHANGED: 15,
  MULTIPLE_FAILED_LOGINS: 25,
  SENSITIVE_RESOURCE_ACCESS: 30,
  UNAUTHORIZED_RESOURCE_ACCESS: 40,
  SUSPICIOUS_ACTIVITY: 25,
  SESSION_ANOMALY: 20
};